/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWebsiteIndexRouteImport } from './routes/_authenticated/website/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedShippingIndexRouteImport } from './routes/_authenticated/shipping/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPushStatusIndexRouteImport } from './routes/_authenticated/push-status/index'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated/proposals/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPickListsIndexRouteImport } from './routes/_authenticated/pick-lists/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedOrderDeskIndexRouteImport } from './routes/_authenticated/order-desk/index'
import { Route as AuthenticatedNavOptionsIndexRouteImport } from './routes/_authenticated/nav-options/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCreateIndexRouteImport } from './routes/_authenticated/create/index'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog/index'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated/calendar/index'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity/index'
import { Route as AuthSignInIndexRouteImport } from './routes/_auth/sign-in/index'
import { Route as AuthenticatedDocumentsNewRouteImport } from './routes/_authenticated/documents/new'
import { Route as AuthenticatedTasksTaskIdIndexRouteImport } from './routes/_authenticated/tasks/$taskId/index'
import { Route as AuthenticatedProposalsProposalIdIndexRouteImport } from './routes/_authenticated/proposals/$proposalId/index'
import { Route as AuthenticatedPickListsPickListIdIndexRouteImport } from './routes/_authenticated/pick-lists/$pickListId/index'
import { Route as AuthenticatedOrdersOrderIdIndexRouteImport } from './routes/_authenticated/orders/$orderId/index'
import { Route as AuthenticatedDocumentsTemplateIdIndexRouteImport } from './routes/_authenticated/documents/$templateId/index'
import { Route as AuthenticatedCustomersCustomerIdIndexRouteImport } from './routes/_authenticated/customers/$customerId/index'
import { Route as AuthenticatedCatalogSpecsIndexRouteImport } from './routes/_authenticated/catalog/specs/index'
import { Route as AuthenticatedCatalogVpVpIdIndexRouteImport } from './routes/_authenticated/catalog/vp/$vpId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsiteIndexRoute =
  AuthenticatedWebsiteIndexRouteImport.update({
    id: '/website/',
    path: '/website/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShippingIndexRoute =
  AuthenticatedShippingIndexRouteImport.update({
    id: '/shipping/',
    path: '/shipping/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPushStatusIndexRoute =
  AuthenticatedPushStatusIndexRouteImport.update({
    id: '/push-status/',
    path: '/push-status/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPickListsIndexRoute =
  AuthenticatedPickListsIndexRouteImport.update({
    id: '/pick-lists/',
    path: '/pick-lists/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrderDeskIndexRoute =
  AuthenticatedOrderDeskIndexRouteImport.update({
    id: '/order-desk/',
    path: '/order-desk/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNavOptionsIndexRoute =
  AuthenticatedNavOptionsIndexRouteImport.update({
    id: '/nav-options/',
    path: '/nav-options/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreateIndexRoute =
  AuthenticatedCreateIndexRouteImport.update({
    id: '/create/',
    path: '/create/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthenticatedDocumentsNewRoute =
  AuthenticatedDocumentsNewRouteImport.update({
    id: '/documents/new',
    path: '/documents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksTaskIdIndexRoute =
  AuthenticatedTasksTaskIdIndexRouteImport.update({
    id: '/tasks/$taskId/',
    path: '/tasks/$taskId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsProposalIdIndexRoute =
  AuthenticatedProposalsProposalIdIndexRouteImport.update({
    id: '/proposals/$proposalId/',
    path: '/proposals/$proposalId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPickListsPickListIdIndexRoute =
  AuthenticatedPickListsPickListIdIndexRouteImport.update({
    id: '/pick-lists/$pickListId/',
    path: '/pick-lists/$pickListId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdIndexRoute =
  AuthenticatedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsTemplateIdIndexRoute =
  AuthenticatedDocumentsTemplateIdIndexRouteImport.update({
    id: '/documents/$templateId/',
    path: '/documents/$templateId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdIndexRoute =
  AuthenticatedCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogSpecsIndexRoute =
  AuthenticatedCatalogSpecsIndexRouteImport.update({
    id: '/catalog/specs/',
    path: '/catalog/specs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogVpVpIdIndexRoute =
  AuthenticatedCatalogVpVpIdIndexRouteImport.update({
    id: '/catalog/vp/$vpId/',
    path: '/catalog/vp/$vpId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/activity/': typeof AuthenticatedActivityIndexRoute
  '/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/create/': typeof AuthenticatedCreateIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/nav-options/': typeof AuthenticatedNavOptionsIndexRoute
  '/order-desk/': typeof AuthenticatedOrderDeskIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/pick-lists/': typeof AuthenticatedPickListsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/push-status/': typeof AuthenticatedPushStatusIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shipping/': typeof AuthenticatedShippingIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/website/': typeof AuthenticatedWebsiteIndexRoute
  '/catalog/specs/': typeof AuthenticatedCatalogSpecsIndexRoute
  '/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/documents/$templateId/': typeof AuthenticatedDocumentsTemplateIdIndexRoute
  '/orders/$orderId/': typeof AuthenticatedOrdersOrderIdIndexRoute
  '/pick-lists/$pickListId/': typeof AuthenticatedPickListsPickListIdIndexRoute
  '/proposals/$proposalId/': typeof AuthenticatedProposalsProposalIdIndexRoute
  '/tasks/$taskId/': typeof AuthenticatedTasksTaskIdIndexRoute
  '/catalog/vp/$vpId/': typeof AuthenticatedCatalogVpVpIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/create': typeof AuthenticatedCreateIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/dev': typeof AuthenticatedDevIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/nav-options': typeof AuthenticatedNavOptionsIndexRoute
  '/order-desk': typeof AuthenticatedOrderDeskIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/pick-lists': typeof AuthenticatedPickListsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
  '/push-status': typeof AuthenticatedPushStatusIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shipping': typeof AuthenticatedShippingIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/website': typeof AuthenticatedWebsiteIndexRoute
  '/catalog/specs': typeof AuthenticatedCatalogSpecsIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/documents/$templateId': typeof AuthenticatedDocumentsTemplateIdIndexRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdIndexRoute
  '/pick-lists/$pickListId': typeof AuthenticatedPickListsPickListIdIndexRoute
  '/proposals/$proposalId': typeof AuthenticatedProposalsProposalIdIndexRoute
  '/tasks/$taskId': typeof AuthenticatedTasksTaskIdIndexRoute
  '/catalog/vp/$vpId': typeof AuthenticatedCatalogVpVpIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/documents/new': typeof AuthenticatedDocumentsNewRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/create/': typeof AuthenticatedCreateIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/nav-options/': typeof AuthenticatedNavOptionsIndexRoute
  '/_authenticated/order-desk/': typeof AuthenticatedOrderDeskIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/pick-lists/': typeof AuthenticatedPickListsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/_authenticated/push-status/': typeof AuthenticatedPushStatusIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/shipping/': typeof AuthenticatedShippingIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/website/': typeof AuthenticatedWebsiteIndexRoute
  '/_authenticated/catalog/specs/': typeof AuthenticatedCatalogSpecsIndexRoute
  '/_authenticated/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/_authenticated/documents/$templateId/': typeof AuthenticatedDocumentsTemplateIdIndexRoute
  '/_authenticated/orders/$orderId/': typeof AuthenticatedOrdersOrderIdIndexRoute
  '/_authenticated/pick-lists/$pickListId/': typeof AuthenticatedPickListsPickListIdIndexRoute
  '/_authenticated/proposals/$proposalId/': typeof AuthenticatedProposalsProposalIdIndexRoute
  '/_authenticated/tasks/$taskId/': typeof AuthenticatedTasksTaskIdIndexRoute
  '/_authenticated/catalog/vp/$vpId/': typeof AuthenticatedCatalogVpVpIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents/new'
    | '/sign-in/'
    | '/activity/'
    | '/calendar/'
    | '/catalog/'
    | '/create/'
    | '/customers/'
    | '/dev/'
    | '/documents/'
    | '/nav-options/'
    | '/order-desk/'
    | '/orders/'
    | '/pick-lists/'
    | '/profile/'
    | '/projects/'
    | '/proposals/'
    | '/push-status/'
    | '/settings/'
    | '/shipping/'
    | '/tasks/'
    | '/users/'
    | '/website/'
    | '/catalog/specs/'
    | '/customers/$customerId/'
    | '/documents/$templateId/'
    | '/orders/$orderId/'
    | '/pick-lists/$pickListId/'
    | '/proposals/$proposalId/'
    | '/tasks/$taskId/'
    | '/catalog/vp/$vpId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents/new'
    | '/sign-in'
    | '/activity'
    | '/calendar'
    | '/catalog'
    | '/create'
    | '/customers'
    | '/dev'
    | '/documents'
    | '/nav-options'
    | '/order-desk'
    | '/orders'
    | '/pick-lists'
    | '/profile'
    | '/projects'
    | '/proposals'
    | '/push-status'
    | '/settings'
    | '/shipping'
    | '/tasks'
    | '/users'
    | '/website'
    | '/catalog/specs'
    | '/customers/$customerId'
    | '/documents/$templateId'
    | '/orders/$orderId'
    | '/pick-lists/$pickListId'
    | '/proposals/$proposalId'
    | '/tasks/$taskId'
    | '/catalog/vp/$vpId'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/documents/new'
    | '/_auth/sign-in/'
    | '/_authenticated/activity/'
    | '/_authenticated/calendar/'
    | '/_authenticated/catalog/'
    | '/_authenticated/create/'
    | '/_authenticated/customers/'
    | '/_authenticated/dev/'
    | '/_authenticated/documents/'
    | '/_authenticated/nav-options/'
    | '/_authenticated/order-desk/'
    | '/_authenticated/orders/'
    | '/_authenticated/pick-lists/'
    | '/_authenticated/profile/'
    | '/_authenticated/projects/'
    | '/_authenticated/proposals/'
    | '/_authenticated/push-status/'
    | '/_authenticated/settings/'
    | '/_authenticated/shipping/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/website/'
    | '/_authenticated/catalog/specs/'
    | '/_authenticated/customers/$customerId/'
    | '/_authenticated/documents/$templateId/'
    | '/_authenticated/orders/$orderId/'
    | '/_authenticated/pick-lists/$pickListId/'
    | '/_authenticated/proposals/$proposalId/'
    | '/_authenticated/tasks/$taskId/'
    | '/_authenticated/catalog/vp/$vpId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website/': {
      id: '/_authenticated/website/'
      path: '/website'
      fullPath: '/website/'
      preLoaderRoute: typeof AuthenticatedWebsiteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipping/': {
      id: '/_authenticated/shipping/'
      path: '/shipping'
      fullPath: '/shipping/'
      preLoaderRoute: typeof AuthenticatedShippingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/push-status/': {
      id: '/_authenticated/push-status/'
      path: '/push-status'
      fullPath: '/push-status/'
      preLoaderRoute: typeof AuthenticatedPushStatusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pick-lists/': {
      id: '/_authenticated/pick-lists/'
      path: '/pick-lists'
      fullPath: '/pick-lists/'
      preLoaderRoute: typeof AuthenticatedPickListsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order-desk/': {
      id: '/_authenticated/order-desk/'
      path: '/order-desk'
      fullPath: '/order-desk/'
      preLoaderRoute: typeof AuthenticatedOrderDeskIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nav-options/': {
      id: '/_authenticated/nav-options/'
      path: '/nav-options'
      fullPath: '/nav-options/'
      preLoaderRoute: typeof AuthenticatedNavOptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create/': {
      id: '/_authenticated/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof AuthenticatedCreateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_authenticated/documents/new': {
      id: '/_authenticated/documents/new'
      path: '/documents/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AuthenticatedDocumentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/$taskId/': {
      id: '/_authenticated/tasks/$taskId/'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId/'
      preLoaderRoute: typeof AuthenticatedTasksTaskIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$proposalId/': {
      id: '/_authenticated/proposals/$proposalId/'
      path: '/proposals/$proposalId'
      fullPath: '/proposals/$proposalId/'
      preLoaderRoute: typeof AuthenticatedProposalsProposalIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pick-lists/$pickListId/': {
      id: '/_authenticated/pick-lists/$pickListId/'
      path: '/pick-lists/$pickListId'
      fullPath: '/pick-lists/$pickListId/'
      preLoaderRoute: typeof AuthenticatedPickListsPickListIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId/': {
      id: '/_authenticated/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$templateId/': {
      id: '/_authenticated/documents/$templateId/'
      path: '/documents/$templateId'
      fullPath: '/documents/$templateId/'
      preLoaderRoute: typeof AuthenticatedDocumentsTemplateIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId/': {
      id: '/_authenticated/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId/'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/specs/': {
      id: '/_authenticated/catalog/specs/'
      path: '/catalog/specs'
      fullPath: '/catalog/specs/'
      preLoaderRoute: typeof AuthenticatedCatalogSpecsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog/vp/$vpId/': {
      id: '/_authenticated/catalog/vp/$vpId/'
      path: '/catalog/vp/$vpId'
      fullPath: '/catalog/vp/$vpId/'
      preLoaderRoute: typeof AuthenticatedCatalogVpVpIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentsNewRoute: typeof AuthenticatedDocumentsNewRoute
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedCreateIndexRoute: typeof AuthenticatedCreateIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedNavOptionsIndexRoute: typeof AuthenticatedNavOptionsIndexRoute
  AuthenticatedOrderDeskIndexRoute: typeof AuthenticatedOrderDeskIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedPickListsIndexRoute: typeof AuthenticatedPickListsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
  AuthenticatedPushStatusIndexRoute: typeof AuthenticatedPushStatusIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedShippingIndexRoute: typeof AuthenticatedShippingIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWebsiteIndexRoute: typeof AuthenticatedWebsiteIndexRoute
  AuthenticatedCatalogSpecsIndexRoute: typeof AuthenticatedCatalogSpecsIndexRoute
  AuthenticatedCustomersCustomerIdIndexRoute: typeof AuthenticatedCustomersCustomerIdIndexRoute
  AuthenticatedDocumentsTemplateIdIndexRoute: typeof AuthenticatedDocumentsTemplateIdIndexRoute
  AuthenticatedOrdersOrderIdIndexRoute: typeof AuthenticatedOrdersOrderIdIndexRoute
  AuthenticatedPickListsPickListIdIndexRoute: typeof AuthenticatedPickListsPickListIdIndexRoute
  AuthenticatedProposalsProposalIdIndexRoute: typeof AuthenticatedProposalsProposalIdIndexRoute
  AuthenticatedTasksTaskIdIndexRoute: typeof AuthenticatedTasksTaskIdIndexRoute
  AuthenticatedCatalogVpVpIdIndexRoute: typeof AuthenticatedCatalogVpVpIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentsNewRoute: AuthenticatedDocumentsNewRoute,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedCreateIndexRoute: AuthenticatedCreateIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedNavOptionsIndexRoute: AuthenticatedNavOptionsIndexRoute,
  AuthenticatedOrderDeskIndexRoute: AuthenticatedOrderDeskIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedPickListsIndexRoute: AuthenticatedPickListsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
  AuthenticatedPushStatusIndexRoute: AuthenticatedPushStatusIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedShippingIndexRoute: AuthenticatedShippingIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWebsiteIndexRoute: AuthenticatedWebsiteIndexRoute,
  AuthenticatedCatalogSpecsIndexRoute: AuthenticatedCatalogSpecsIndexRoute,
  AuthenticatedCustomersCustomerIdIndexRoute:
    AuthenticatedCustomersCustomerIdIndexRoute,
  AuthenticatedDocumentsTemplateIdIndexRoute:
    AuthenticatedDocumentsTemplateIdIndexRoute,
  AuthenticatedOrdersOrderIdIndexRoute: AuthenticatedOrdersOrderIdIndexRoute,
  AuthenticatedPickListsPickListIdIndexRoute:
    AuthenticatedPickListsPickListIdIndexRoute,
  AuthenticatedProposalsProposalIdIndexRoute:
    AuthenticatedProposalsProposalIdIndexRoute,
  AuthenticatedTasksTaskIdIndexRoute: AuthenticatedTasksTaskIdIndexRoute,
  AuthenticatedCatalogVpVpIdIndexRoute: AuthenticatedCatalogVpVpIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
